# Generated by Django 5.0.7 on 2024-08-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240805_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_data',
            field=models.DateTimeField(null=True),
        ),
    ]
