# Generated by Django 5.0.7 on 2024-08-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_birth_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_data',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
